### ISSUE TITLE
Contact Form Submission - Other

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#3251] opened 2022-12-05 14:34 UTC
Someone submitted the contact form!

**URL**: https://usaco.guide/settings/#user-data
**Module**: None
**Topic**: Other
**Message**: 
I am having issue with registration. After register page I never got password.

**Comment by SansPapyrus683** [comment] 2022-12-05 15:39
dupe of #3087

**Closed by SansPapyrus683** 2022-12-05 15:39 UTC
