### ISSUE TITLE
Contact Form Submission - Website Bug

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#3887] opened 2023-08-18 17:21 UTC
Someone submitted the contact form!

**URL**: https://usaco.guide/silver/
**Module**: None
**Topic**: Website Bug
**Message**: 
I almost finish the silver section and i've solved most of the problems but all my progress have gone, i marked all the problems that i solved, and i wanted to came back again to solve the harder ones that i couldn't solve them but now i can't know what problems i solve and what not :'(

**Comment by SansPapyrus683** [comment] 2023-08-18 17:23
dupe of #3425

**Closed by SansPapyrus683** 2023-08-18 17:23 UTC
Labels: bug, website

**Comment by bqi343** [comment] 2023-08-18 21:42
It would be great if you could answer the questions in https://github.com/cpinitiative/usaco-guide/issues/3396#issuecomment-1414102550

**Comment by Abode200** [comment] 2023-08-22 22:48
i'm sorry for being too late 
1- i am signing in with Google 
2- i think i created my account five or six months ago but i'm not sure 
3- i found this issue 4 days ago, when i send this message 
4-I just signed in as usual 
5-Yes all my data is lost
