### ISSUE TITLE
Contact Form Submission - Suggestion

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#3344] opened 2023-01-10 21:10 UTC
Someone submitted the contact form!

**URL**: https://usaco.guide/gold/dp-ranges?lang=cpp
**Module**: Gold - Range DP
**Topic**: Suggestion
**Message**: 
please add this problem
https://codeforces.com/contest/1132/problem/F
my CF: https://codeforces.com/profile/__Davit__

**Comment by bqi343** [comment] 2023-01-11 00:59
Duplicate of #3345

**Closed by bqi343** 2023-01-11 00:59 UTC
