### ISSUE TITLE
Contact Form Submission - Other

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#2370] opened 2021-12-01 01:06 UTC
Someone submitted the contact form!

**Module**: General - Using This Guide
**Topic**: Other
**Message**: 
I was wondering if someone could please tell me how I would delete my account.

**Comment by SansPapyrus683** [comment] 2021-12-01 02:51
dupe of #2369

**Closed by SansPapyrus683** 2021-12-01 02:51 UTC
