### ISSUE TITLE
Some starred problems don't have solutions

### ISSUE THREAD

**Issue by Aadit-Ambadkar** [cpinitiative/usaco-guide#2603] opened 2022-03-02 04:44 UTC
Ex:
https://usaco.guide/gold/dp-bitmasks#problem-coci-16-burza

I'll add more later.

**Comment by SansPapyrus683** [comment] 2022-03-03 01:50
lmfao

**Comment by SansPapyrus683** [comment] 2022-05-13 16:12
current problem is dupe of #2639

**Closed by SansPapyrus683** 2022-05-13 16:12 UTC
