### ISSUE TITLE
Parallel Binary Search

### ISSUE THREAD

**Issue by Usernametaken12** [cpinitiative/usaco-guide#4951] opened 2024-11-30 05:01 UTC
Would it be worthwhile to add a section to the page on persistence to include parallel binary search? 

I don't think this warrants it's own page as I'm not sure how common this technique. Given that most things which can be solved with it can be solved by a persistent version of a given data structure, it would make the most sense to be added here.

A section would be roughly based around this blog:
https://codeforces.com/blog/entry/45578 (should probably be re-written in the guide. The blog, while it gets the point across, would be much better with illustrations)

Problems:
https://oj.uz/problem/view/JOI23_currencies (HLD + parallel binary search)
https://evaluator.hsin.hr/tasks/HONI202167index/ (move from persistence, can be solved in O( (Q+N) log N) time with parallel binary search + prefix sums)

(from the blog)
https://www.spoj.com/problems/METEORS/
https://www.hackerearth.com/challenges/competitive/may-circuits/algorithm/make-n00b_land-great-again-circuits/
https://community.topcoder.com/stat?c=problem_statement&pm=14088

I haven't done all the persistence problems in the guide, so if any can be better solved with parallel binary search please suggest them (or other problems?).

**Comment by SansPapyrus683** [comment] 2024-11-30 18:58
dupe of #3624

**Closed by SansPapyrus683** 2024-11-30 18:58 UTC
