### ISSUE TITLE
Contact Form Submission - Typo / Broken Link

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#2449] opened 2021-12-29 04:09 UTC
Someone submitted the contact form!

**Module**: Silver - Two Pointers
**Topic**: Typo / Broken Link
**Message**: 
`CF Edu` link in `Resources` is broken- the website reports a `No such course` error.

**Comment by bqi343** [comment] 2021-12-31 02:49
Similar to #2455

**Comment by SansPapyrus683** [comment] 2022-05-13 17:59
dupe of #2455

**Closed by SansPapyrus683** 2022-05-13 17:59 UTC
Labels: bug
