### ISSUE TITLE
Contact Form Submission - Website Bug

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#2894] opened 2022-07-01 15:36 UTC
Someone submitted the contact form!

**URL**: https://usaco.guide/gold/lis?lang=cpp
**Module**: None
**Topic**: Website Bug
**Message**: 
Hello there,

I am following this guide since quite long time and it's really the best source to prepare for IOI and practice competitive programming. I recently faced a bug. All of a sudden the status of all the questions changed to "NOT ATTEMPTED". This has happened with me 2 times. 

Kindly fix the bug

Thank you

**Comment by SansPapyrus683** [comment] 2022-07-01 18:36
if we could have some more information that'd be nice

**Comment by bqi343** [comment] 2022-07-02 15:21
Duplicate of #2541

**Closed by bqi343** 2022-07-02 15:21 UTC
