### ISSUE TITLE
Contact Form Submission - Suggestion

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#3950] opened 2023-09-17 03:56 UTC
Someone submitted the contact form!

**URL**: https://usaco.guide/problems/
**Module**: None
**Topic**: Suggestion
**Message**: 
It would be cool to be able to add notes to a problem within USACO Guide as a sort of journal of problems.

**Comment by SansPapyrus683** [comment] 2023-09-17 04:39
dupe of #2954

**Closed by SansPapyrus683** 2023-09-17 04:39 UTC
Labels: enhancement
