### ISSUE TITLE
Contact Form Submission - Website Bug

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#3938] opened 2023-09-12 16:09 UTC
Someone submitted the contact form!

**URL**: https://usaco.guide/dashboard
**Module**: None
**Topic**: Website Bug
**Message**: 
Cow pictures aren't showing up! Counter is negative right now. Before that I could refresh to see a new cow photo whenever I wanted to. I guess it's kinda broken.

**Comment by 3centroids** [comment] 2023-09-12 16:12
<img width="613" alt="Screenshot 2023-09-12 at 18 10 24" src="https://github.com/cpinitiative/usaco-guide/assets/85312805/4cf9f476-1ca8-4868-914c-5c00f1aa68f8">

**Comment by SansPapyrus683** [comment] 2023-09-12 21:58
dupe of #3734

**Closed by SansPapyrus683** 2023-09-12 21:58 UTC
Labels: bug, website
