### ISSUE TITLE
Contact Form Submission - Request - Missing Section or Editorial

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#2378] opened 2021-12-04 03:31 UTC
Someone submitted the contact form!

**Module**: Gold - Minimum Spanning Trees
**Topic**: Request - Missing Section or Editorial
**Message**: 
The current link to problem JOI 2015 - Inheritance has no english statement, and I have found one online so I want to contribute. 
Here is the link: https://hackmd.io/HfPKcvJqSNSfU4gTvevUlQ?view

**Comment by SansPapyrus683** [comment] 2021-12-05 00:59
...
where the hell
that's LITERALLY MY TRANSLATION WHAT

**Comment by SansPapyrus683** [comment] 2021-12-05 00:59
anyways, dupe of #2301

**Closed by SansPapyrus683** 2021-12-05 00:59 UTC
