### ISSUE TITLE
Contact Form Submission - Website Bug

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#3246] opened 2022-12-03 10:05 UTC
Someone submitted the contact form!

**URL**: https://usaco.guide/dashboard
**Module**: None
**Topic**: Website Bug
**Message**: 
I registered for new account a few days ago.
However, I haven't received any email about the password until now. I tried to find in the spam mail, but i couldn't find any email from you. Please send temporary password and help me to log on the USACO.org my username is: mateuszwojaczek

**Comment by SansPapyrus683** [comment] 2022-12-03 17:30
dupe of #3087

**Closed by SansPapyrus683** 2022-12-03 17:30 UTC
