### ISSUE TITLE
Cow photo countdown bug

### ISSUE THREAD

**Issue by dolphingarlic** [cpinitiative/usaco-guide#518] opened 2020-12-23 16:05 UTC
> The counter for the new cow picture is not reflective of the number of days till the next cow picture. It has a countdown which is always less than 24 hours

**Comment by bqi343** [comment] 2020-12-23 16:18
I think this was intended by @thecodingwizard so the streak would continue if a user visits < 24 hours later.

**Comment by thecodingwizard** [comment] 2020-12-23 20:17
Crap I don't remember since I'm on a 124 day streak ;) ;)

**Comment by bqi343** [comment] 2020-12-24 14:34
@thecodingwizard so are we closing this?

**Comment by thecodingwizard** [comment] 2020-12-24 20:13
Uhhh I think this is a valid bug... I'm not sure what the best solution is though? Because simply updating the timer to be until the next prime day won't work -- they need to visit every day. Maybe we should show both the countdown and how many days left?

**Comment by bqi343** [comment] 2020-12-24 23:35
Currently it says `to continue your streak` instead of `to unlock this cow photo` when there's > 1 day, which I think is fine?

**Comment by bqi343** [comment] 2020-12-27 00:07
Closed by 0808e89

**Closed by bqi343** 2020-12-27 00:07 UTC
Labels: backlog, bug, website
