### ISSUE TITLE
Contact Form Submission - Website Bug

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#3249] opened 2022-12-04 04:28 UTC
Someone submitted the contact form!

**URL**: https://usaco.guide/
**Module**: None
**Topic**: Website Bug
**Message**: 
I have trouble resetting my password. Whenever I hit the submit button on the forgot password page, the email or a form isn't sent to my gmail account.

**Comment by bqi343** [comment] 2022-12-04 04:40
duplicate of https://github.com/cpinitiative/usaco-guide/issues/2854#issuecomment-1162802123

**Closed by bqi343** 2022-12-04 04:40 UTC
