### ISSUE TITLE
Contact Form Submission - Website Bug

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#2834] opened 2022-06-12 00:50 UTC
Someone submitted the contact form!

**URL**: https://usaco.guide/gold/
**Module**: Advanced Section
**Topic**: Website Bug
**Message**: 
The drop down menu that normally appears when selecting the division on the top banner (between USACO guide and the problems link) simply doesn't work when you are viewing the advanced section.

**Comment by maggie-j-liu** [comment] 2022-06-12 01:43
hmm, it works for me?

https://user-images.githubusercontent.com/63619830/173210656-f9c6aa43-e376-4219-af3b-c4c24bf6390f.mov

**Comment by SansPapyrus683** [comment] 2022-06-12 05:14
same here

**Comment by bqi343** [comment] 2022-06-18 18:39
Closing due to insufficient information to reproduce, feel free to reopen if you have more info.

**Closed by bqi343** 2022-06-18 18:39 UTC
Labels: bug
