### ISSUE TITLE
Contact Form Submission - Website Bug

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#3931] opened 2023-09-09 15:00 UTC
Someone submitted the contact form!

**URL**: https://usaco.guide/dashboard/
**Module**: None
**Topic**: Website Bug
**Message**: 
Day 2 Photo:
Come back in
-5 hours -20 minutes -45 seconds
to continue your streak! Photo will be unlocked after -3 days.

**Comment by tsktsktsktsk** [comment] 2023-09-09 15:01
![image](https://github.com/cpinitiative/usaco-guide/assets/106004804/6949224a-4812-452d-a3e6-82a4ebc27c65)

**Comment by bqi343** [comment] 2023-09-10 05:14
Same as #3734. Idk how to fix this, but if you have any ideas why this is happening or have a way to consistently reproduce this that would be great.

**Comment by tsktsktsktsk** [comment] 2023-09-10 11:08
Even force reloading the page won't fix it.

I finally managed to fix it by exporting and then importing user data.

Still don't know what went wrong & haven't found a way to reproduce it though.

**Comment by SansPapyrus683** [comment] 2023-09-11 01:22
if it's a dupe of #3734 we can close this right

**Closed by SansPapyrus683** 2023-09-11 01:22 UTC
Labels: bug, website
