### ISSUE TITLE
Contact Form Submission - Website Bug

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#3933] opened 2023-09-11 03:02 UTC
Someone submitted the contact form!

**URL**: https://usaco.guide/dashboard/
**Module**: None
**Topic**: Website Bug
**Message**: 
Hi guys,
This is to inform you that for some reason the streaks feature has some sort of bug. On my account, it says "come back in -2 Days and -22 hours to continue your streak", and the counter is reversed. 

Kinda funny, but would be nice if it's fixed :)

Also letting you know that this website has proved to be quite helpful for me. In a sense you guys have completed your goal for being the "one stop shop", well done!

Thanks,
Arag (seriouslyFlawed)

**Comment by SansPapyrus683** [comment] 2023-09-11 03:32
dupe of #3734

**Closed by SansPapyrus683** 2023-09-11 03:32 UTC
Labels: bug, website
