### ISSUE TITLE
No Email Upon Account Creation

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#2876] opened 2022-06-23 15:38 UTC
Someone submitted the contact form!

**URL**: https://usaco.guide/dashboard/
**Module**: None
**Topic**: Other
**Message**: 
I have created my account but I didnot get any email regarding setting the password.

**Comment by SansPapyrus683** [comment] 2022-06-23 23:02
wha
why are so many submissions about this these days

**Comment by bqi343** [comment] 2022-07-14 13:51
I assume this is a duplicate of #2854, feel free to reopen if not.

**Closed by bqi343** 2022-07-14 13:51 UTC
Labels: bug
