### ISSUE TITLE
Contact Form Submission - Typo / Broken Link

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#2951] opened 2022-07-21 19:01 UTC
Someone submitted the contact form!

**URL**: https://usaco.guide/groups/wxfeD9sIjPGRSRpeSGsM/edit
**Module**: None
**Topic**: Typo / Broken Link
**Message**: 
i did not get password . i am unable to practice problem .please help me

**Comment by bqi343** [comment] 2022-07-21 19:05
Duplicate of https://github.com/cpinitiative/usaco-guide/issues/2854 I think?

**Closed by bqi343** 2022-07-21 19:05 UTC
